### ISSUE TITLE
Radius setup map does not function

### ISSUE THREAD

**Issue by Randomballoon** [SilphRoad/reports#1]
## I'm submitting a ...
  - [X] bug report
  - [ ] feature request

The map on the Radius setup page is not functioning correctly for me. The map either loads to a completely grey map of the world I can more around, or a zoomed in map of somewhere but the map is locked and I cannot interact with it (zoom, pan, etc).

I have tried F5, CTRL+F5, cleared cache, restarted browser, enabling WebGL, and hardware acceleration is enabled. This page also works:
https://www.mapbox.com/mapbox-gl-js/example/check-for-support/

- Operating System:  Windows 10 Home 64-bit
- Browser:   Chrome Version 59.0.3071.115 (Official Build) (64-bit) with all extensions disabled and in Incognito Mode.

![image](https://user-images.githubusercontent.com/7347157/27766053-6d214fc4-5e89-11e7-95c8-ac9c5e64cb63.png)

**Comment by Randomballoon** [comment]
Found this error in the console:

```
radio:20 GET https://www.googletagmanager.com/gtm.js?id=GTM-ML6238Q 
(anonymous) @ radio:20
(anonymous) @ radio:21

radio-v0.1.min.js:1 Refused to handle connected
radio-v0.1.min.js:1 Refused to handle auth

mapbox-gl.js?1498065314:128 Uncaught Error: Invalid LngLat object: (NaN, NaN)
    at new LngLat (mapbox-gl.js?1498065314:128)
    at Function.LngLat.convert (mapbox-gl.js?1498065314:128)
    at LngLatBounds.setSouthWest (mapbox-gl.js?1498065314:130)
    at new LngLatBounds (mapbox-gl.js?1498065314:130)
    at renderRadiusPolygon (radio:1427)
    at e.<anonymous> (radio:1368)
    at e.Evented.fire (mapbox-gl.js?1498065314:411)
    at e._render (mapbox-gl.js?1498065314:385)
```

**Comment by dronpes** [comment]
We've pushed a few fixes that may have resolved this. Can you take a look and let us know if there are any more issues? You can re-visit the page here:

https://TheSilphRoad.com/radio?prefs

**Comment by adrazich** [comment]
I was able to replicate this issue again this morning. I cleared out my cache before attempting. I still get the same error in console that @Randomballoon is seeing. It seems to not happen every time but roughly every other time. I've tested on both Windows and Mac and have the same issue.

**Comment by Randomballoon** [comment]
I was able to set up preferences on mobile this morning while I couldn't last night, but I'm having similar problems still on desktop Windows 10 Chrome with a slightly different error this time:

https://thesilphroad.com/radio?prefs#13/30.3298/-97.7037

gtm.js Failed to load resource: the server responded with a status of 404 ()
radio:1625 Quota exceeded!
radio-v0.1.min.js:1 Refused to handle connected
radio-v0.1.min.js:1 Refused to handle auth

VM4122:1 [Deprecation] 'window.webkitStorageInfo' is deprecated. Please use 'navigator.webkitTemporaryStorage' or 'navigator.webkitPersistentStorage' instead.
(anonymous) @ VM4122:1

mapbox-gl.js:128 Uncaught Error: Invalid LngLat object: (NaN, NaN)
    at new LngLat (mapbox-gl.js:128)
    at Function.LngLat.convert (mapbox-gl.js:128)
    at LngLatBounds.setSouthWest (mapbox-gl.js:130)
    at new LngLatBounds (mapbox-gl.js:130)
    at renderRadiusPolygon (radio:1430)
    at e.<anonymous> (radio:1371)
    at e.Evented.fire (mapbox-gl.js:411)
    at e._render (mapbox-gl.js:385)

**Comment by w0jnar** [comment]
Had similiar issues. Dronpes asked for some STR. Admittedly, wasn't anything out of the  ordinary.
Attempted to access https://thesilphroad.com/radio
First via the link on https://thesilphroad.com header then via the direct link https://thesilphroad.com/radio

Upon directing to the page, even before clicking "Set My Radius!" the file has already failed to load with a 404 error.
Specifically, the block:
	
	<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
	new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
	j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
	'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
	})(window,document,'script','dataLayer','GTM-ML6238Q');</script>

**Comment by Randomballoon** [comment]
Was able to successfully set my radius today, maybe because of a Radio update being pushed. New error below but I don't see any visible issues, again on Win 10 Chrome.

radio?prefs:20 GET https://www.googletagmanager.com/gtm.js?id=GTM-ML6238Q 
(anonymous) @ radio?prefs:20
(anonymous) @ radio?prefs:21

radio?prefs:1613 Quota exceeded!
radio-v0.1.min.js:1 Refused to handle connected
radio-v0.1.min.js:1 Refused to handle auth

**Comment by marcoceppi** [comment]
These errors are expected. thanks!
